$axure.loadCurrentPage({
  "url":"公司文化.html",
  "generationDate":new Date(1525678702457.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"16b597f36ac54d0c8280427a4df09070",
    "type":"Axure:Page",
    "name":"公司文化",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a316c64594bb4952862c203175574e20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":604},
            "size":{
              "width":1365,
              "height":826},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da20f58520204554b3a319a8d4c5eccf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":604},
                "size":{
                  "width":1365,
                  "height":826},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司文化/u0.png"}},
{
          "id":"93ba95cc233f452ea1d82bebac9df9a6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fb9b5a49173d4bb0beea9bbd7bae152b"},
{
          "id":"5315bd73345448e2ad89ca9bbf0d9b18",
          "label":"主页信息区",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":99},
            "size":{
              "width":1365,
              "height":26}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"569cf458700e4e939f64f5f6232bdf75",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"55fdf6b0a99c4adca73f49ce16e23477",
                  "label":"",
                  "parentDynamicPanel":"5315bd73345448e2ad89ca9bbf0d9b18",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1365,
                      "height":27},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a92c20a6975f45b2b0aff008c9dc3359",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5315bd73345448e2ad89ca9bbf0d9b18",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1365,
                          "height":27},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u119.png"}},
{
                  "id":"96c0064486634aed847f62cd40691d7b",
                  "label":"",
                  "parentDynamicPanel":"5315bd73345448e2ad89ca9bbf0d9b18",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":58,
                      "y":4},
                    "size":{
                      "width":710,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"56aefedac47f4e0a917dd60b2d7782ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5315bd73345448e2ad89ca9bbf0d9b18",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":58,
                          "y":4},
                        "size":{
                          "width":710,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"841046a36db04794b3a9a41092ce4c1b",
                  "label":"",
                  "parentDynamicPanel":"5315bd73345448e2ad89ca9bbf0d9b18",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":24,
                      "y":1},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"46b64b750cfe47609beffef4ad9f1461",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5315bd73345448e2ad89ca9bbf0d9b18",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":24,
                          "y":1},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u123.png"}}]}]},
{
          "id":"bf77e9363cc8403eba21cdaf7b1cae18",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":125},
            "size":{
              "width":1365,
              "height":479}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ef9a3cde8fc43baad125f7b5c968c11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":125},
                "size":{
                  "width":1365,
                  "height":479}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司文化/u38.png"}},
{
          "id":"59f7f90832d6416dac83bbf11560a73e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":472,
              "y":639},
            "size":{
              "width":421,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"156247b1c2584416bbaed939a7c3ffc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":472,
                  "y":639},
                "size":{
                  "width":421,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"019342b7860447cab51de6102f415184",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":740},
            "size":{
              "width":650,
              "height":650}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0808c9d3a253490086c5f7f1d4759991",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":740},
                "size":{
                  "width":650,
                  "height":650}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司文化/u42.png"}},
{
          "id":"b34fddffd8034aa794bf54ae68eea5bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "location":{
              "x":720,
              "y":740},
            "size":{
              "width":603,
              "height":490}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71ed92e9181147e8aeaa97640ceeacbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "location":{
                  "x":720,
                  "y":740},
                "size":{
                  "width":603,
                  "height":490}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f7b0c23a053c4eeea3f2cf1bec3a413d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1430},
            "size":{
              "width":1365,
              "height":640},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81942f7e199848acb0f515ccc65ad6c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1430},
                "size":{
                  "width":1365,
                  "height":640},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司文化/u46.png"}},
{
          "id":"c7659b573a3445dcb4714e8a014d4ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"35px",
            "location":{
              "x":615.5,
              "y":1470},
            "size":{
              "width":246,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34903762cf0b4968902cdd0b1c4c296d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"35px",
                "location":{
                  "x":615.5,
                  "y":1470},
                "size":{
                  "width":246,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"484a773d616b4e6a9bf144f458687e51",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":291,
              "y":1582},
            "size":{
              "width":88,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"795e21fd61f2427199401717ea9d8819",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":291,
                  "y":1582},
                "size":{
                  "width":88,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司文化/u50.png"}},
{
          "id":"8ed8f93240ea403a8bc5528c22d07291",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":978,
              "y":1582},
            "size":{
              "width":88,
              "height":88}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9ca24c754f44dea8192feda36ddf573",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":978,
                  "y":1582},
                "size":{
                  "width":88,
                  "height":88}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司文化/u52.png"}},
{
          "id":"49a4083e2a6144c5bd93bc30b783b64e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":64,
              "y":1710},
            "size":{
              "width":542,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f75669fedc924a93bb9a39738a9b0536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":64,
                  "y":1710},
                "size":{
                  "width":542,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b85df64baacd457791f6d33477850ef4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":751,
              "y":1710},
            "size":{
              "width":542,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f091970d1d840fc8cdd92464ea32e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":751,
                  "y":1710},
                "size":{
                  "width":542,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c9a295617dda4d108b3df3e96f9f46c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2070},
            "size":{
              "width":1365,
              "height":590},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10faed4e84cc4e5a824dea1f1c0d320d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":2070},
                "size":{
                  "width":1365,
                  "height":590},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司文化/u58.png"}},
{
          "id":"e75966a101e74460bb7e3d014272021d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2070}},
          "adaptiveStyles":{
},
          "masterId":"fe2b4986fdef41cba8d905cdf795056c"},
{
          "id":"e96eb75739c34c7783c0487edfca265f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":2115},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"scrollToWidget",
                      "description":"滚动到 导航条/顶部 (仅垂直)",
                      "objectPath":["93ba95cc233f452ea1d82bebac9df9a6",
"8700267c6f1343b7a211cc25494ff284"],
                      "options":{
                        "direction":"vertical"}}]}]}},
          "tabbable":true}]}},
  "masters":{
    "fb9b5a49173d4bb0beea9bbd7bae152b":{
      "packageId":"fb9b5a49173d4bb0beea9bbd7bae152b",
      "type":"Axure:Master",
      "name":"导航条",
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5631e6ecaf9440eaae5931ca06a9f535",
            "label":"头部遮罩",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x33000000},
              "size":{
                "width":1365,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ea6259cec19c443f849a434cbd04825c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x33000000},
                  "size":{
                    "width":1365,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/头部遮罩_u20.png"}},
{
            "id":"79068d9ae58f4c3192680e3f0e28ecbb",
            "label":"顶部菜单",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":825,
                "y":0},
              "size":{
                "width":540,
                "height":100}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"d04d361dbe7045e3a3f1159cf0926b4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"19823130cab34e0c8ae77ac0cb06d779",
                    "label":"首页按钮",
                    "parentDynamicPanel":"79068d9ae58f4c3192680e3f0e28ecbb",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":26},
                      "size":{
                        "width":100,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 丝路千寻-东欧模特培训及引进，外籍模特经纪",
                                "target":{
                                  "targetType":"page",
                                  "url":"丝路千寻-东欧模特培训及引进，外籍模特经纪.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 首页按钮 to 浮动后",
                                "panelsToStates":[{
                                    "panelPath":["19823130cab34e0c8ae77ac0cb06d779"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 首页按钮 to 浮动前",
                                "panelsToStates":[{
                                    "panelPath":["19823130cab34e0c8ae77ac0cb06d779"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5ec6622f429144b7b528e72445dd825d",
                        "label":"浮动前",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"bbaf3b6aada44bf6a92fceeae3f8b129",
                            "label":"",
                            "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":24,
                                "y":9},
                              "size":{
                                "width":53,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"622a3a1a54c04914a621f1f1302fcb54",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":24,
                                    "y":9},
                                  "size":{
                                    "width":53,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]},
{
                        "id":"d2ed63497c38417aaa09364737e9464f",
                        "label":"浮动后",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"53d201151a7b4adb8df958052cd47d4e",
                            "label":"",
                            "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600,
                                "opacity":1},
                              "location":{
                                "x":24,
                                "y":9},
                              "size":{
                                "width":53,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"60035da982434ca997404b20a47e367c",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFF6600,
                                    "opacity":1},
                                  "location":{
                                    "x":24,
                                    "y":9},
                                  "size":{
                                    "width":53,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"ad3686c6ed1a4dedb77d22be683cbccb",
                            "label":"",
                            "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                            "type":"horizontalLine",
                            "styleType":"horizontalLine",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":24,
                                "y":0},
                              "size":{
                                "width":53,
                                "height":10},
                              "borderWidth":"2",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600}},
                            "adaptiveStyles":{
},
                            "images":{
                              "start~":"resources/images/transparent.gif",
                              "end~":"resources/images/transparent.gif",
                              "line~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u28_line.png"}}]}]},
{
                    "id":"a65db00bb5ff49ba8f32112ff89b207e",
                    "label":"模特库按钮",
                    "parentDynamicPanel":"79068d9ae58f4c3192680e3f0e28ecbb",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":153,
                        "y":26},
                      "size":{
                        "width":100,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 模特库",
                                "target":{
                                  "targetType":"page",
                                  "url":"模特库.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 模特库按钮 to 浮动后",
                                "panelsToStates":[{
                                    "panelPath":["a65db00bb5ff49ba8f32112ff89b207e"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 模特库按钮 to 浮动前",
                                "panelsToStates":[{
                                    "panelPath":["a65db00bb5ff49ba8f32112ff89b207e"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"ca4424f1b1b943e3bb1eccfb1ee9f248",
                        "label":"浮动前",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"43e72f1f0005441181bba1fa27e6ee15",
                            "label":"",
                            "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":11,
                                "y":9},
                              "size":{
                                "width":79,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"9de0f3555a5f42d08260d0724f92ab87",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":11,
                                    "y":9},
                                  "size":{
                                    "width":79,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]},
{
                        "id":"d30392902f3e4b509c4bad1dd0cd2a94",
                        "label":"浮动后",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"79e6ee0fbe064a46a21bc442b95d0bc3",
                            "label":"",
                            "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600,
                                "opacity":1},
                              "location":{
                                "x":11,
                                "y":9},
                              "size":{
                                "width":79,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"264abbc17d924d4c97f35331fdc277b8",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFF6600,
                                    "opacity":1},
                                  "location":{
                                    "x":11,
                                    "y":9},
                                  "size":{
                                    "width":79,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"bf2a22e52f844460a718993c8410788c",
                            "label":"",
                            "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                            "type":"horizontalLine",
                            "styleType":"horizontalLine",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":12,
                                "y":0},
                              "size":{
                                "width":76,
                                "height":10},
                              "borderWidth":"2",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600}},
                            "adaptiveStyles":{
},
                            "images":{
                              "start~":"resources/images/transparent.gif",
                              "end~":"resources/images/transparent.gif",
                              "line~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u34_line.png"}}]}]},
{
                    "id":"548cb0aab7f64327a07d75bc2b0b1356",
                    "label":"视频按钮",
                    "parentDynamicPanel":"79068d9ae58f4c3192680e3f0e28ecbb",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":420,
                        "y":26},
                      "size":{
                        "width":100,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 作品库",
                                "target":{
                                  "targetType":"page",
                                  "url":"作品库.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 视频按钮 to 浮动后",
                                "panelsToStates":[{
                                    "panelPath":["548cb0aab7f64327a07d75bc2b0b1356"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 视频按钮 to 浮动前",
                                "panelsToStates":[{
                                    "panelPath":["548cb0aab7f64327a07d75bc2b0b1356"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"b6aefbe354a14c10aa07b49059926632",
                        "label":"浮动前",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"4a528cc57ff24ac2898a52e82c39152d",
                            "label":"",
                            "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":11,
                                "y":9},
                              "size":{
                                "width":79,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"2691b304bf8e4434b7a41d6dae7ede99",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":11,
                                    "y":9},
                                  "size":{
                                    "width":79,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]},
{
                        "id":"d80e7dfdbdd846bcbef7cd6dfe71f8b4",
                        "label":"浮动后",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"64f0afdb592a406fb495b1609cd0408f",
                            "label":"",
                            "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600,
                                "opacity":1},
                              "location":{
                                "x":11,
                                "y":9},
                              "size":{
                                "width":79,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"2b6c1d76dfe04f8eac2568c0a32f5f85",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFF6600,
                                    "opacity":1},
                                  "location":{
                                    "x":11,
                                    "y":9},
                                  "size":{
                                    "width":79,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"a632f645ea9f4b32a3e3b8c6d50264d3",
                            "label":"",
                            "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                            "type":"horizontalLine",
                            "styleType":"horizontalLine",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":11,
                                "y":0},
                              "size":{
                                "width":79,
                                "height":10},
                              "borderWidth":"2",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600}},
                            "adaptiveStyles":{
},
                            "images":{
                              "start~":"resources/images/transparent.gif",
                              "end~":"resources/images/transparent.gif",
                              "line~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u40_line.png"}}]}]},
{
                    "id":"a91b2c57aa5e4a36b3f14cc13f33210a",
                    "label":"日程按钮",
                    "parentDynamicPanel":"79068d9ae58f4c3192680e3f0e28ecbb",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":287,
                        "y":26},
                      "size":{
                        "width":100,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 花系模特",
                                "target":{
                                  "targetType":"page",
                                  "url":"花系模特.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 日程按钮 to 浮动后",
                                "panelsToStates":[{
                                    "panelPath":["a91b2c57aa5e4a36b3f14cc13f33210a"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 日程按钮 to 浮动前",
                                "panelsToStates":[{
                                    "panelPath":["a91b2c57aa5e4a36b3f14cc13f33210a"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"9f5055a963b249139694b7eb5248f213",
                        "label":"浮动前",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"0aeb00ca046a4142a4bec860d1753c92",
                            "label":"",
                            "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":24,
                                "y":9},
                              "size":{
                                "width":53,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"e7fa992b715d43c99c9442696907c334",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":24,
                                    "y":9},
                                  "size":{
                                    "width":53,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]},
{
                        "id":"1be09a8c740349b4987e6e53db249ed0",
                        "label":"浮动后",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"ab992dda862c46e88fda19a6c8441653",
                            "label":"",
                            "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600,
                                "opacity":1},
                              "location":{
                                "x":24,
                                "y":9},
                              "size":{
                                "width":53,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6967c1551f734fffa8da256b65075d9b",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFF6600,
                                    "opacity":1},
                                  "location":{
                                    "x":24,
                                    "y":9},
                                  "size":{
                                    "width":53,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"cb93506577044cef86f3d5ac6e92cd78",
                            "label":"",
                            "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                            "type":"horizontalLine",
                            "styleType":"horizontalLine",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":24,
                                "y":0},
                              "size":{
                                "width":53,
                                "height":10},
                              "borderWidth":"2",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600}},
                            "adaptiveStyles":{
},
                            "images":{
                              "start~":"resources/images/transparent.gif",
                              "end~":"resources/images/transparent.gif",
                              "line~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u28_line.png"}}]}]}]}]},
{
            "id":"8700267c6f1343b7a211cc25494ff284",
            "label":"顶部",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":0},
              "size":{
                "width":20,
                "height":40}},
            "adaptiveStyles":{
}}]}},
    "fe2b4986fdef41cba8d905cdf795056c":{
      "packageId":"fe2b4986fdef41cba8d905cdf795056c",
      "type":"Axure:Master",
      "name":"底部",
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b7785e9d2e6a49aca406f53d6f924851",
            "label":"底部区域",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":1365,
                "height":370}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"55917df952df4738a5ab74ad2a4b0cff",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b1341f40113f419e9af2752826f0c534",
                    "label":"",
                    "parentDynamicPanel":"b7785e9d2e6a49aca406f53d6f924851",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0x332F2B27},
                      "size":{
                        "width":1365,
                        "height":370},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFC9C9C9}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d029cb6546ab4e8cae770216ad9d6263",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7785e9d2e6a49aca406f53d6f924851",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0x332F2B27},
                          "size":{
                            "width":1365,
                            "height":370},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFC9C9C9}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u127.png"}}]}]},
{
            "id":"7f2a2ba172f54acf9bf1d6d0b430e30e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":57,
                "y":40},
              "size":{
                "width":61,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3eadbca54f3d4537aff64fb6b5978c57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":57,
                    "y":40},
                  "size":{
                    "width":61,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"62fd41699c954d0fb612cef060b46ef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":57,
                "y":90},
              "size":{
                "width":41,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa13ba85e89845ffbfb32f73dd892ca4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":57,
                    "y":90},
                  "size":{
                    "width":41,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"df4232565b4a46b9b508029e996451f3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":120},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4b3fdcc376c84d7a9f9200149b3e626f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":120},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d3297c8ffea4c94a74ca46571b1537f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":143},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5e8078e3d104c93ad62e36ae79b5874",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":143},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e8a621d6f359406bad01dc9733916d37",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":57,
                "y":187},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6a70f1d77306400d9dd317b2626bbb0d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":57,
                    "y":187},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"870501b4f6134f73a637925d66fdb0e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":219},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bce01167942740019607018f9eb19491",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":219},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ebe42f958c3d4fb38496f21ddc2f3c0a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":242},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a4324f8c878743c8b8555c41adf6793d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":242},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"db3d9cee97c747ba8521af9b2cc0e0ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":267},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b091ec9335f049f0a8be4ec82d3ca2ec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":267},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0586ca2bd784cf2b58489b4a7353d4d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":79,
                "y":292},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c23aac14db4d4a529f24af0a1025ede7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":79,
                    "y":292},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d48c2b42fec34ca68fe0cf688d2554b0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":79,
                "y":319},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0d68a742589d415a9e049b503e0a4b0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":79,
                    "y":319},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4acfbe03aff74eb498e6b381fae17210",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":219},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
}},
{
            "id":"84c6cc5f56f24bca99a758e16de8d13c",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":244},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 服务理念",
                        "target":{
                          "targetType":"page",
                          "url":"服务理念.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"4f0eeee0a23b47e2aa773550698122aa",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":270},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公司文化",
                        "target":{
                          "targetType":"page",
                          "url":"公司文化.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2da5b915b36048889cf675b2af178034",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":293},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 人员招聘",
                        "target":{
                          "targetType":"page",
                          "url":"人员招聘.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"d3682f82358540a1a10dcf407e952c71",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":320},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 交流合作",
                        "target":{
                          "targetType":"page",
                          "url":"交流合作.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9281a91613344715810be8f5a83c441b",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":120},
              "size":{
                "width":80,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公司新闻",
                        "target":{
                          "targetType":"page",
                          "url":"公司新闻.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"04aced1416f048b89f4103ad0c2f6b7c",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":147},
              "size":{
                "width":80,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 第三批东欧模特抵京",
                        "target":{
                          "targetType":"page",
                          "url":"第三批东欧模特抵京.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "a316c64594bb4952862c203175574e20":{
      "scriptId":"u0"},
    "da20f58520204554b3a319a8d4c5eccf":{
      "scriptId":"u1"},
    "93ba95cc233f452ea1d82bebac9df9a6":{
      "scriptId":"u2",
      "5631e6ecaf9440eaae5931ca06a9f535":{
        "scriptId":"u3"},
      "ea6259cec19c443f849a434cbd04825c":{
        "scriptId":"u4"},
      "79068d9ae58f4c3192680e3f0e28ecbb":{
        "scriptId":"u5"},
      "19823130cab34e0c8ae77ac0cb06d779":{
        "scriptId":"u6"},
      "bbaf3b6aada44bf6a92fceeae3f8b129":{
        "scriptId":"u7"},
      "622a3a1a54c04914a621f1f1302fcb54":{
        "scriptId":"u8"},
      "53d201151a7b4adb8df958052cd47d4e":{
        "scriptId":"u9"},
      "60035da982434ca997404b20a47e367c":{
        "scriptId":"u10"},
      "ad3686c6ed1a4dedb77d22be683cbccb":{
        "scriptId":"u11"},
      "a65db00bb5ff49ba8f32112ff89b207e":{
        "scriptId":"u12"},
      "43e72f1f0005441181bba1fa27e6ee15":{
        "scriptId":"u13"},
      "9de0f3555a5f42d08260d0724f92ab87":{
        "scriptId":"u14"},
      "79e6ee0fbe064a46a21bc442b95d0bc3":{
        "scriptId":"u15"},
      "264abbc17d924d4c97f35331fdc277b8":{
        "scriptId":"u16"},
      "bf2a22e52f844460a718993c8410788c":{
        "scriptId":"u17"},
      "548cb0aab7f64327a07d75bc2b0b1356":{
        "scriptId":"u18"},
      "4a528cc57ff24ac2898a52e82c39152d":{
        "scriptId":"u19"},
      "2691b304bf8e4434b7a41d6dae7ede99":{
        "scriptId":"u20"},
      "64f0afdb592a406fb495b1609cd0408f":{
        "scriptId":"u21"},
      "2b6c1d76dfe04f8eac2568c0a32f5f85":{
        "scriptId":"u22"},
      "a632f645ea9f4b32a3e3b8c6d50264d3":{
        "scriptId":"u23"},
      "a91b2c57aa5e4a36b3f14cc13f33210a":{
        "scriptId":"u24"},
      "0aeb00ca046a4142a4bec860d1753c92":{
        "scriptId":"u25"},
      "e7fa992b715d43c99c9442696907c334":{
        "scriptId":"u26"},
      "ab992dda862c46e88fda19a6c8441653":{
        "scriptId":"u27"},
      "6967c1551f734fffa8da256b65075d9b":{
        "scriptId":"u28"},
      "cb93506577044cef86f3d5ac6e92cd78":{
        "scriptId":"u29"},
      "8700267c6f1343b7a211cc25494ff284":{
        "scriptId":"u30"}},
    "5315bd73345448e2ad89ca9bbf0d9b18":{
      "scriptId":"u31"},
    "55fdf6b0a99c4adca73f49ce16e23477":{
      "scriptId":"u32"},
    "a92c20a6975f45b2b0aff008c9dc3359":{
      "scriptId":"u33"},
    "96c0064486634aed847f62cd40691d7b":{
      "scriptId":"u34"},
    "56aefedac47f4e0a917dd60b2d7782ec":{
      "scriptId":"u35"},
    "841046a36db04794b3a9a41092ce4c1b":{
      "scriptId":"u36"},
    "46b64b750cfe47609beffef4ad9f1461":{
      "scriptId":"u37"},
    "bf77e9363cc8403eba21cdaf7b1cae18":{
      "scriptId":"u38"},
    "5ef9a3cde8fc43baad125f7b5c968c11":{
      "scriptId":"u39"},
    "59f7f90832d6416dac83bbf11560a73e":{
      "scriptId":"u40"},
    "156247b1c2584416bbaed939a7c3ffc2":{
      "scriptId":"u41"},
    "019342b7860447cab51de6102f415184":{
      "scriptId":"u42"},
    "0808c9d3a253490086c5f7f1d4759991":{
      "scriptId":"u43"},
    "b34fddffd8034aa794bf54ae68eea5bc":{
      "scriptId":"u44"},
    "71ed92e9181147e8aeaa97640ceeacbe":{
      "scriptId":"u45"},
    "f7b0c23a053c4eeea3f2cf1bec3a413d":{
      "scriptId":"u46"},
    "81942f7e199848acb0f515ccc65ad6c0":{
      "scriptId":"u47"},
    "c7659b573a3445dcb4714e8a014d4ac2":{
      "scriptId":"u48"},
    "34903762cf0b4968902cdd0b1c4c296d":{
      "scriptId":"u49"},
    "484a773d616b4e6a9bf144f458687e51":{
      "scriptId":"u50"},
    "795e21fd61f2427199401717ea9d8819":{
      "scriptId":"u51"},
    "8ed8f93240ea403a8bc5528c22d07291":{
      "scriptId":"u52"},
    "a9ca24c754f44dea8192feda36ddf573":{
      "scriptId":"u53"},
    "49a4083e2a6144c5bd93bc30b783b64e":{
      "scriptId":"u54"},
    "f75669fedc924a93bb9a39738a9b0536":{
      "scriptId":"u55"},
    "b85df64baacd457791f6d33477850ef4":{
      "scriptId":"u56"},
    "7f091970d1d840fc8cdd92464ea32e05":{
      "scriptId":"u57"},
    "c9a295617dda4d108b3df3e96f9f46c4":{
      "scriptId":"u58"},
    "10faed4e84cc4e5a824dea1f1c0d320d":{
      "scriptId":"u59"},
    "e75966a101e74460bb7e3d014272021d":{
      "scriptId":"u60",
      "b7785e9d2e6a49aca406f53d6f924851":{
        "scriptId":"u61"},
      "b1341f40113f419e9af2752826f0c534":{
        "scriptId":"u62"},
      "d029cb6546ab4e8cae770216ad9d6263":{
        "scriptId":"u63"},
      "7f2a2ba172f54acf9bf1d6d0b430e30e":{
        "scriptId":"u64"},
      "3eadbca54f3d4537aff64fb6b5978c57":{
        "scriptId":"u65"},
      "62fd41699c954d0fb612cef060b46ef4":{
        "scriptId":"u66"},
      "fa13ba85e89845ffbfb32f73dd892ca4":{
        "scriptId":"u67"},
      "df4232565b4a46b9b508029e996451f3":{
        "scriptId":"u68"},
      "4b3fdcc376c84d7a9f9200149b3e626f":{
        "scriptId":"u69"},
      "5d3297c8ffea4c94a74ca46571b1537f":{
        "scriptId":"u70"},
      "d5e8078e3d104c93ad62e36ae79b5874":{
        "scriptId":"u71"},
      "e8a621d6f359406bad01dc9733916d37":{
        "scriptId":"u72"},
      "6a70f1d77306400d9dd317b2626bbb0d":{
        "scriptId":"u73"},
      "870501b4f6134f73a637925d66fdb0e2":{
        "scriptId":"u74"},
      "bce01167942740019607018f9eb19491":{
        "scriptId":"u75"},
      "ebe42f958c3d4fb38496f21ddc2f3c0a":{
        "scriptId":"u76"},
      "a4324f8c878743c8b8555c41adf6793d":{
        "scriptId":"u77"},
      "db3d9cee97c747ba8521af9b2cc0e0ec":{
        "scriptId":"u78"},
      "b091ec9335f049f0a8be4ec82d3ca2ec":{
        "scriptId":"u79"},
      "c0586ca2bd784cf2b58489b4a7353d4d":{
        "scriptId":"u80"},
      "c23aac14db4d4a529f24af0a1025ede7":{
        "scriptId":"u81"},
      "d48c2b42fec34ca68fe0cf688d2554b0":{
        "scriptId":"u82"},
      "0d68a742589d415a9e049b503e0a4b0f":{
        "scriptId":"u83"},
      "4acfbe03aff74eb498e6b381fae17210":{
        "scriptId":"u84"},
      "84c6cc5f56f24bca99a758e16de8d13c":{
        "scriptId":"u85"},
      "4f0eeee0a23b47e2aa773550698122aa":{
        "scriptId":"u86"},
      "2da5b915b36048889cf675b2af178034":{
        "scriptId":"u87"},
      "d3682f82358540a1a10dcf407e952c71":{
        "scriptId":"u88"},
      "9281a91613344715810be8f5a83c441b":{
        "scriptId":"u89"},
      "04aced1416f048b89f4103ad0c2f6b7c":{
        "scriptId":"u90"}},
    "e96eb75739c34c7783c0487edfca265f":{
      "scriptId":"u91"}}});