$axure.loadCurrentPage({
  "url":"公司介绍.html",
  "generationDate":new Date(1525689295646.57),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cc49f19ebdb648758290cd57d461211a",
    "type":"Axure:Page",
    "name":"公司介绍",
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"15536a854a7d496880a10fb1d58f1115",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"fb9b5a49173d4bb0beea9bbd7bae152b"},
{
          "id":"c640040a1ec64e5fbb1717a9e7070a3e",
          "label":"新闻1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":100},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0ace150779d648928a99cb64b02b9dee",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bc2229a35376473ab689d7a32540bb02",
                  "label":"",
                  "parentDynamicPanel":"c640040a1ec64e5fbb1717a9e7070a3e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":1365,
                      "height":920},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"100292aad5744348b454e0dbb70cfce9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c640040a1ec64e5fbb1717a9e7070a3e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":1365,
                          "height":920},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/作品库/作品库首页作品集封面_u91.png"}},
{
                  "id":"e335022bc29b41e9b0d2cc9cb35e4375",
                  "label":"",
                  "parentDynamicPanel":"c640040a1ec64e5fbb1717a9e7070a3e",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":634,
                      "y":32},
                    "size":{
                      "width":97,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9e6e512df3404145bf16571626400732",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c640040a1ec64e5fbb1717a9e7070a3e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":634,
                          "y":32},
                        "size":{
                          "width":97,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2bc50d4233ce48d4ae2a24f3733cac98",
                  "label":"",
                  "parentDynamicPanel":"c640040a1ec64e5fbb1717a9e7070a3e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":666,
                      "y":144},
                    "size":{
                      "width":664,
                      "height":486}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6f5624397424ada8ce2c52a9b6b8e54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c640040a1ec64e5fbb1717a9e7070a3e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":666,
                          "y":144},
                        "size":{
                          "width":664,
                          "height":486}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7b5a1ef0b692488cb4a997171f733cd6",
                  "label":"",
                  "parentDynamicPanel":"c640040a1ec64e5fbb1717a9e7070a3e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":37,
                      "y":144},
                    "size":{
                      "width":593,
                      "height":395}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33fcd51e5ea24b2facd4895389ccbdae",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c640040a1ec64e5fbb1717a9e7070a3e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":37,
                          "y":144},
                        "size":{
                          "width":593,
                          "height":395}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/第二次东欧女模大集结盛大举行/u38.png"}}]}]},
{
          "id":"a99e2bb20c5442b39d22b48b6d135649",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1020}},
          "adaptiveStyles":{
},
          "masterId":"fe2b4986fdef41cba8d905cdf795056c"},
{
          "id":"9d790ec4fe4c4e4ca30f4535d8a3517c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":1064},
            "size":{
              "width":60,
              "height":20}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"scrollToWidget",
                      "description":"滚动到 导航条/顶部 (仅垂直)",
                      "objectPath":["15536a854a7d496880a10fb1d58f1115",
"8700267c6f1343b7a211cc25494ff284"],
                      "options":{
                        "direction":"vertical"}}]}]}},
          "tabbable":true}]}},
  "masters":{
    "fb9b5a49173d4bb0beea9bbd7bae152b":{
      "packageId":"fb9b5a49173d4bb0beea9bbd7bae152b",
      "type":"Axure:Master",
      "name":"导航条",
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"5631e6ecaf9440eaae5931ca06a9f535",
            "label":"头部遮罩",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x33000000},
              "size":{
                "width":1365,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ea6259cec19c443f849a434cbd04825c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x33000000},
                  "size":{
                    "width":1365,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/头部遮罩_u20.png"}},
{
            "id":"79068d9ae58f4c3192680e3f0e28ecbb",
            "label":"顶部菜单",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "location":{
                "x":825,
                "y":0},
              "size":{
                "width":540,
                "height":100}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"d04d361dbe7045e3a3f1159cf0926b4b",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"19823130cab34e0c8ae77ac0cb06d779",
                    "label":"首页按钮",
                    "parentDynamicPanel":"79068d9ae58f4c3192680e3f0e28ecbb",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":20,
                        "y":26},
                      "size":{
                        "width":100,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 丝路千寻-东欧模特培训及引进，外籍模特经纪",
                                "target":{
                                  "targetType":"page",
                                  "url":"丝路千寻-东欧模特培训及引进，外籍模特经纪.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 首页按钮 to 浮动后",
                                "panelsToStates":[{
                                    "panelPath":["19823130cab34e0c8ae77ac0cb06d779"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 首页按钮 to 浮动前",
                                "panelsToStates":[{
                                    "panelPath":["19823130cab34e0c8ae77ac0cb06d779"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"5ec6622f429144b7b528e72445dd825d",
                        "label":"浮动前",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"bbaf3b6aada44bf6a92fceeae3f8b129",
                            "label":"",
                            "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":24,
                                "y":9},
                              "size":{
                                "width":53,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"622a3a1a54c04914a621f1f1302fcb54",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":24,
                                    "y":9},
                                  "size":{
                                    "width":53,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]},
{
                        "id":"d2ed63497c38417aaa09364737e9464f",
                        "label":"浮动后",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"53d201151a7b4adb8df958052cd47d4e",
                            "label":"",
                            "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600,
                                "opacity":1},
                              "location":{
                                "x":24,
                                "y":9},
                              "size":{
                                "width":53,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"60035da982434ca997404b20a47e367c",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFF6600,
                                    "opacity":1},
                                  "location":{
                                    "x":24,
                                    "y":9},
                                  "size":{
                                    "width":53,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"ad3686c6ed1a4dedb77d22be683cbccb",
                            "label":"",
                            "parentDynamicPanel":"19823130cab34e0c8ae77ac0cb06d779",
                            "type":"horizontalLine",
                            "styleType":"horizontalLine",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":24,
                                "y":0},
                              "size":{
                                "width":53,
                                "height":10},
                              "borderWidth":"2",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600}},
                            "adaptiveStyles":{
},
                            "images":{
                              "start~":"resources/images/transparent.gif",
                              "end~":"resources/images/transparent.gif",
                              "line~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u28_line.png"}}]}]},
{
                    "id":"a65db00bb5ff49ba8f32112ff89b207e",
                    "label":"模特库按钮",
                    "parentDynamicPanel":"79068d9ae58f4c3192680e3f0e28ecbb",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":153,
                        "y":26},
                      "size":{
                        "width":100,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 模特库",
                                "target":{
                                  "targetType":"page",
                                  "url":"模特库.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 模特库按钮 to 浮动后",
                                "panelsToStates":[{
                                    "panelPath":["a65db00bb5ff49ba8f32112ff89b207e"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 模特库按钮 to 浮动前",
                                "panelsToStates":[{
                                    "panelPath":["a65db00bb5ff49ba8f32112ff89b207e"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"ca4424f1b1b943e3bb1eccfb1ee9f248",
                        "label":"浮动前",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"43e72f1f0005441181bba1fa27e6ee15",
                            "label":"",
                            "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":11,
                                "y":9},
                              "size":{
                                "width":79,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"9de0f3555a5f42d08260d0724f92ab87",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":11,
                                    "y":9},
                                  "size":{
                                    "width":79,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]},
{
                        "id":"d30392902f3e4b509c4bad1dd0cd2a94",
                        "label":"浮动后",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"79e6ee0fbe064a46a21bc442b95d0bc3",
                            "label":"",
                            "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600,
                                "opacity":1},
                              "location":{
                                "x":11,
                                "y":9},
                              "size":{
                                "width":79,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"264abbc17d924d4c97f35331fdc277b8",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFF6600,
                                    "opacity":1},
                                  "location":{
                                    "x":11,
                                    "y":9},
                                  "size":{
                                    "width":79,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"bf2a22e52f844460a718993c8410788c",
                            "label":"",
                            "parentDynamicPanel":"a65db00bb5ff49ba8f32112ff89b207e",
                            "type":"horizontalLine",
                            "styleType":"horizontalLine",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":12,
                                "y":0},
                              "size":{
                                "width":76,
                                "height":10},
                              "borderWidth":"2",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600}},
                            "adaptiveStyles":{
},
                            "images":{
                              "start~":"resources/images/transparent.gif",
                              "end~":"resources/images/transparent.gif",
                              "line~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u34_line.png"}}]}]},
{
                    "id":"548cb0aab7f64327a07d75bc2b0b1356",
                    "label":"视频按钮",
                    "parentDynamicPanel":"79068d9ae58f4c3192680e3f0e28ecbb",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":420,
                        "y":26},
                      "size":{
                        "width":100,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 作品库",
                                "target":{
                                  "targetType":"page",
                                  "url":"作品库.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 视频按钮 to 浮动后",
                                "panelsToStates":[{
                                    "panelPath":["548cb0aab7f64327a07d75bc2b0b1356"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 视频按钮 to 浮动前",
                                "panelsToStates":[{
                                    "panelPath":["548cb0aab7f64327a07d75bc2b0b1356"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"b6aefbe354a14c10aa07b49059926632",
                        "label":"浮动前",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"4a528cc57ff24ac2898a52e82c39152d",
                            "label":"",
                            "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":11,
                                "y":9},
                              "size":{
                                "width":79,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"2691b304bf8e4434b7a41d6dae7ede99",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":11,
                                    "y":9},
                                  "size":{
                                    "width":79,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]},
{
                        "id":"d80e7dfdbdd846bcbef7cd6dfe71f8b4",
                        "label":"浮动后",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"64f0afdb592a406fb495b1609cd0408f",
                            "label":"",
                            "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600,
                                "opacity":1},
                              "location":{
                                "x":11,
                                "y":9},
                              "size":{
                                "width":79,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"2b6c1d76dfe04f8eac2568c0a32f5f85",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFF6600,
                                    "opacity":1},
                                  "location":{
                                    "x":11,
                                    "y":9},
                                  "size":{
                                    "width":79,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"a632f645ea9f4b32a3e3b8c6d50264d3",
                            "label":"",
                            "parentDynamicPanel":"548cb0aab7f64327a07d75bc2b0b1356",
                            "type":"horizontalLine",
                            "styleType":"horizontalLine",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":11,
                                "y":0},
                              "size":{
                                "width":79,
                                "height":10},
                              "borderWidth":"2",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600}},
                            "adaptiveStyles":{
},
                            "images":{
                              "start~":"resources/images/transparent.gif",
                              "end~":"resources/images/transparent.gif",
                              "line~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u40_line.png"}}]}]},
{
                    "id":"a91b2c57aa5e4a36b3f14cc13f33210a",
                    "label":"日程按钮",
                    "parentDynamicPanel":"79068d9ae58f4c3192680e3f0e28ecbb",
                    "type":"dynamicPanel",
                    "styleType":"dynamicPanel",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":287,
                        "y":26},
                      "size":{
                        "width":100,
                        "height":50}},
                    "adaptiveStyles":{
},
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 花系模特",
                                "target":{
                                  "targetType":"page",
                                  "url":"花系模特.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]},
                      "onMouseOver":{
                        "description":"OnMouseOver",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 日程按钮 to 浮动后",
                                "panelsToStates":[{
                                    "panelPath":["a91b2c57aa5e4a36b3f14cc13f33210a"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":2,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]},
                      "onMouseOut":{
                        "description":"OnMouseOut",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"setPanelState",
                                "description":"设置 日程按钮 to 浮动前",
                                "panelsToStates":[{
                                    "panelPath":["a91b2c57aa5e4a36b3f14cc13f33210a"],
                                    "stateInfo":{
                                      "setStateType":"diagram",
                                      "stateNumber":1,
                                      "stateValue":{
                                        "exprType":"stringLiteral",
                                        "value":"1",
                                        "stos":[]},
                                      "loop":false,
                                      "showWhenSet":false,
                                      "options":{
                                        "compress":false}}}]}]}]}},
                    "tabbable":true,
                    "scrollbars":"none",
                    "fitToContent":false,
                    "propagate":false,
                    "diagrams":[{
                        "id":"9f5055a963b249139694b7eb5248f213",
                        "label":"浮动前",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"0aeb00ca046a4142a4bec860d1753c92",
                            "label":"",
                            "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFFFFFF,
                                "opacity":1},
                              "location":{
                                "x":24,
                                "y":9},
                              "size":{
                                "width":53,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"e7fa992b715d43c99c9442696907c334",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFFFFFF,
                                    "opacity":1},
                                  "location":{
                                    "x":24,
                                    "y":9},
                                  "size":{
                                    "width":53,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}}]},
{
                        "id":"1be09a8c740349b4987e6e53db249ed0",
                        "label":"浮动后",
                        "type":"Axure:PanelDiagram",
                        "objects":[{
                            "id":"ab992dda862c46e88fda19a6c8441653",
                            "label":"",
                            "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                            "type":"buttonShape",
                            "styleType":"h1",
                            "visible":true,
                            "style":{
                              "fontSize":"26px",
                              "horizontalAlignment":"center",
                              "foreGroundFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600,
                                "opacity":1},
                              "location":{
                                "x":24,
                                "y":9},
                              "size":{
                                "width":53,
                                "height":32}},
                            "adaptiveStyles":{
},
                            "objects":[{
                                "id":"6967c1551f734fffa8da256b65075d9b",
                                "label":"",
                                "isContained":true,
                                "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                                "type":"richTextPanel",
                                "styleType":"paragraph",
                                "visible":true,
                                "style":{
                                  "fontSize":"26px",
                                  "horizontalAlignment":"center",
                                  "foreGroundFill":{
                                    "fillType":"solid",
                                    "color":0xFFFF6600,
                                    "opacity":1},
                                  "location":{
                                    "x":24,
                                    "y":9},
                                  "size":{
                                    "width":53,
                                    "height":32}},
                                "adaptiveStyles":{
}}],
                            "images":{
                              "normal~":"resources/images/transparent.gif"}},
{
                            "id":"cb93506577044cef86f3d5ac6e92cd78",
                            "label":"",
                            "parentDynamicPanel":"a91b2c57aa5e4a36b3f14cc13f33210a",
                            "type":"horizontalLine",
                            "styleType":"horizontalLine",
                            "visible":true,
                            "style":{
                              "location":{
                                "x":24,
                                "y":0},
                              "size":{
                                "width":53,
                                "height":10},
                              "borderWidth":"2",
                              "borderFill":{
                                "fillType":"solid",
                                "color":0xFFFF6600}},
                            "adaptiveStyles":{
},
                            "images":{
                              "start~":"resources/images/transparent.gif",
                              "end~":"resources/images/transparent.gif",
                              "line~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u28_line.png"}}]}]}]}]},
{
            "id":"8700267c6f1343b7a211cc25494ff284",
            "label":"顶部",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":0},
              "size":{
                "width":20,
                "height":40}},
            "adaptiveStyles":{
}}]}},
    "fe2b4986fdef41cba8d905cdf795056c":{
      "packageId":"fe2b4986fdef41cba8d905cdf795056c",
      "type":"Axure:Master",
      "name":"底部",
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b7785e9d2e6a49aca406f53d6f924851",
            "label":"底部区域",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":1365,
                "height":370}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"55917df952df4738a5ab74ad2a4b0cff",
                "label":"State1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b1341f40113f419e9af2752826f0c534",
                    "label":"",
                    "parentDynamicPanel":"b7785e9d2e6a49aca406f53d6f924851",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0x332F2B27},
                      "size":{
                        "width":1365,
                        "height":370},
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFC9C9C9}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"d029cb6546ab4e8cae770216ad9d6263",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"b7785e9d2e6a49aca406f53d6f924851",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0x332F2B27},
                          "size":{
                            "width":1365,
                            "height":370},
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFC9C9C9}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/丝路千寻-东欧模特培训及引进，外籍模特经纪/u127.png"}}]}]},
{
            "id":"7f2a2ba172f54acf9bf1d6d0b430e30e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":57,
                "y":40},
              "size":{
                "width":61,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3eadbca54f3d4537aff64fb6b5978c57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":57,
                    "y":40},
                  "size":{
                    "width":61,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"62fd41699c954d0fb612cef060b46ef4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":57,
                "y":90},
              "size":{
                "width":41,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fa13ba85e89845ffbfb32f73dd892ca4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":57,
                    "y":90},
                  "size":{
                    "width":41,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"df4232565b4a46b9b508029e996451f3",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":120},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4b3fdcc376c84d7a9f9200149b3e626f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":120},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5d3297c8ffea4c94a74ca46571b1537f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":143},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5e8078e3d104c93ad62e36ae79b5874",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":143},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e8a621d6f359406bad01dc9733916d37",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"20px",
              "fontWeight":"400",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":57,
                "y":187},
              "size":{
                "width":81,
                "height":27}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6a70f1d77306400d9dd317b2626bbb0d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"20px",
                  "fontWeight":"400",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":57,
                    "y":187},
                  "size":{
                    "width":81,
                    "height":27}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"870501b4f6134f73a637925d66fdb0e2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":219},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"bce01167942740019607018f9eb19491",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":219},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ebe42f958c3d4fb38496f21ddc2f3c0a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":242},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a4324f8c878743c8b8555c41adf6793d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":242},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"db3d9cee97c747ba8521af9b2cc0e0ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":80,
                "y":267},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b091ec9335f049f0a8be4ec82d3ca2ec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":80,
                    "y":267},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c0586ca2bd784cf2b58489b4a7353d4d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":79,
                "y":292},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c23aac14db4d4a529f24af0a1025ede7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":79,
                    "y":292},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d48c2b42fec34ca68fe0cf688d2554b0",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "location":{
                "x":79,
                "y":319},
              "size":{
                "width":100,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0d68a742589d415a9e049b503e0a4b0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "location":{
                    "x":79,
                    "y":319},
                  "size":{
                    "width":100,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4acfbe03aff74eb498e6b381fae17210",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":219},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
}},
{
            "id":"84c6cc5f56f24bca99a758e16de8d13c",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":244},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 服务理念",
                        "target":{
                          "targetType":"page",
                          "url":"服务理念.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"4f0eeee0a23b47e2aa773550698122aa",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":270},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公司文化",
                        "target":{
                          "targetType":"page",
                          "url":"公司文化.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"2da5b915b36048889cf675b2af178034",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":293},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 人员招聘",
                        "target":{
                          "targetType":"page",
                          "url":"人员招聘.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"d3682f82358540a1a10dcf407e952c71",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":320},
              "size":{
                "width":70,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 交流合作",
                        "target":{
                          "targetType":"page",
                          "url":"交流合作.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"9281a91613344715810be8f5a83c441b",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":120},
              "size":{
                "width":80,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 公司新闻",
                        "target":{
                          "targetType":"page",
                          "url":"公司新闻.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true},
{
            "id":"04aced1416f048b89f4103ad0c2f6b7c",
            "label":"",
            "type":"imageMapRegion",
            "styleType":"imageMapRegion",
            "visible":true,
            "style":{
              "location":{
                "x":80,
                "y":147},
              "size":{
                "width":80,
                "height":21}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 第三批东欧模特抵京",
                        "target":{
                          "targetType":"page",
                          "url":"第三批东欧模特抵京.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true}]}}},
  "objectPaths":{
    "15536a854a7d496880a10fb1d58f1115":{
      "scriptId":"u0",
      "5631e6ecaf9440eaae5931ca06a9f535":{
        "scriptId":"u1"},
      "ea6259cec19c443f849a434cbd04825c":{
        "scriptId":"u2"},
      "79068d9ae58f4c3192680e3f0e28ecbb":{
        "scriptId":"u3"},
      "19823130cab34e0c8ae77ac0cb06d779":{
        "scriptId":"u4"},
      "bbaf3b6aada44bf6a92fceeae3f8b129":{
        "scriptId":"u5"},
      "622a3a1a54c04914a621f1f1302fcb54":{
        "scriptId":"u6"},
      "53d201151a7b4adb8df958052cd47d4e":{
        "scriptId":"u7"},
      "60035da982434ca997404b20a47e367c":{
        "scriptId":"u8"},
      "ad3686c6ed1a4dedb77d22be683cbccb":{
        "scriptId":"u9"},
      "a65db00bb5ff49ba8f32112ff89b207e":{
        "scriptId":"u10"},
      "43e72f1f0005441181bba1fa27e6ee15":{
        "scriptId":"u11"},
      "9de0f3555a5f42d08260d0724f92ab87":{
        "scriptId":"u12"},
      "79e6ee0fbe064a46a21bc442b95d0bc3":{
        "scriptId":"u13"},
      "264abbc17d924d4c97f35331fdc277b8":{
        "scriptId":"u14"},
      "bf2a22e52f844460a718993c8410788c":{
        "scriptId":"u15"},
      "548cb0aab7f64327a07d75bc2b0b1356":{
        "scriptId":"u16"},
      "4a528cc57ff24ac2898a52e82c39152d":{
        "scriptId":"u17"},
      "2691b304bf8e4434b7a41d6dae7ede99":{
        "scriptId":"u18"},
      "64f0afdb592a406fb495b1609cd0408f":{
        "scriptId":"u19"},
      "2b6c1d76dfe04f8eac2568c0a32f5f85":{
        "scriptId":"u20"},
      "a632f645ea9f4b32a3e3b8c6d50264d3":{
        "scriptId":"u21"},
      "a91b2c57aa5e4a36b3f14cc13f33210a":{
        "scriptId":"u22"},
      "0aeb00ca046a4142a4bec860d1753c92":{
        "scriptId":"u23"},
      "e7fa992b715d43c99c9442696907c334":{
        "scriptId":"u24"},
      "ab992dda862c46e88fda19a6c8441653":{
        "scriptId":"u25"},
      "6967c1551f734fffa8da256b65075d9b":{
        "scriptId":"u26"},
      "cb93506577044cef86f3d5ac6e92cd78":{
        "scriptId":"u27"},
      "8700267c6f1343b7a211cc25494ff284":{
        "scriptId":"u28"}},
    "c640040a1ec64e5fbb1717a9e7070a3e":{
      "scriptId":"u29"},
    "bc2229a35376473ab689d7a32540bb02":{
      "scriptId":"u30"},
    "100292aad5744348b454e0dbb70cfce9":{
      "scriptId":"u31"},
    "e335022bc29b41e9b0d2cc9cb35e4375":{
      "scriptId":"u32"},
    "9e6e512df3404145bf16571626400732":{
      "scriptId":"u33"},
    "2bc50d4233ce48d4ae2a24f3733cac98":{
      "scriptId":"u34"},
    "b6f5624397424ada8ce2c52a9b6b8e54":{
      "scriptId":"u35"},
    "7b5a1ef0b692488cb4a997171f733cd6":{
      "scriptId":"u36"},
    "33fcd51e5ea24b2facd4895389ccbdae":{
      "scriptId":"u37"},
    "a99e2bb20c5442b39d22b48b6d135649":{
      "scriptId":"u38",
      "b7785e9d2e6a49aca406f53d6f924851":{
        "scriptId":"u39"},
      "b1341f40113f419e9af2752826f0c534":{
        "scriptId":"u40"},
      "d029cb6546ab4e8cae770216ad9d6263":{
        "scriptId":"u41"},
      "7f2a2ba172f54acf9bf1d6d0b430e30e":{
        "scriptId":"u42"},
      "3eadbca54f3d4537aff64fb6b5978c57":{
        "scriptId":"u43"},
      "62fd41699c954d0fb612cef060b46ef4":{
        "scriptId":"u44"},
      "fa13ba85e89845ffbfb32f73dd892ca4":{
        "scriptId":"u45"},
      "df4232565b4a46b9b508029e996451f3":{
        "scriptId":"u46"},
      "4b3fdcc376c84d7a9f9200149b3e626f":{
        "scriptId":"u47"},
      "5d3297c8ffea4c94a74ca46571b1537f":{
        "scriptId":"u48"},
      "d5e8078e3d104c93ad62e36ae79b5874":{
        "scriptId":"u49"},
      "e8a621d6f359406bad01dc9733916d37":{
        "scriptId":"u50"},
      "6a70f1d77306400d9dd317b2626bbb0d":{
        "scriptId":"u51"},
      "870501b4f6134f73a637925d66fdb0e2":{
        "scriptId":"u52"},
      "bce01167942740019607018f9eb19491":{
        "scriptId":"u53"},
      "ebe42f958c3d4fb38496f21ddc2f3c0a":{
        "scriptId":"u54"},
      "a4324f8c878743c8b8555c41adf6793d":{
        "scriptId":"u55"},
      "db3d9cee97c747ba8521af9b2cc0e0ec":{
        "scriptId":"u56"},
      "b091ec9335f049f0a8be4ec82d3ca2ec":{
        "scriptId":"u57"},
      "c0586ca2bd784cf2b58489b4a7353d4d":{
        "scriptId":"u58"},
      "c23aac14db4d4a529f24af0a1025ede7":{
        "scriptId":"u59"},
      "d48c2b42fec34ca68fe0cf688d2554b0":{
        "scriptId":"u60"},
      "0d68a742589d415a9e049b503e0a4b0f":{
        "scriptId":"u61"},
      "4acfbe03aff74eb498e6b381fae17210":{
        "scriptId":"u62"},
      "84c6cc5f56f24bca99a758e16de8d13c":{
        "scriptId":"u63"},
      "4f0eeee0a23b47e2aa773550698122aa":{
        "scriptId":"u64"},
      "2da5b915b36048889cf675b2af178034":{
        "scriptId":"u65"},
      "d3682f82358540a1a10dcf407e952c71":{
        "scriptId":"u66"},
      "9281a91613344715810be8f5a83c441b":{
        "scriptId":"u67"},
      "04aced1416f048b89f4103ad0c2f6b7c":{
        "scriptId":"u68"}},
    "9d790ec4fe4c4e4ca30f4535d8a3517c":{
      "scriptId":"u69"}}});